name: Build for Windows 2019

env:
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the workflow will run
on:
  # push:
    # # Sequence of patterns matched against refs/tags
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build tags'

jobs:
  build_windows:
    if: ${{ github.actor == 'badabing2005' }}
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Create virtual environment
        run: python -m venv myenv
        shell: powershell

      - name: Activate virtual environment
        run: .\myenv\Scripts\Activate.ps1
        shell: powershell

      - name: Install wxPython and build
        run: |
          python -m venv myenv
          .\myenv\Scripts\Activate.ps1
          python --version
          pip install -U pip
          pip install -U six wheel setuptools
          pip install -U -f https://extras.wxpython.org/wxPython4/extras/4.2.1 wxPython
        shell: powershell

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: List modules and their versions
        run: pip freeze

      - name: Build application
        run: .\build.bat

      - name: List contents of dist directory
        run: ls dist

      # Upload artifcats Windows to Actions
      - name: Upload Windows Artifact
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }} # Only run this step when running in GitHub Actions
        uses: actions/upload-artifact@v3
        id: upload_artifacts_windows
        with:
          name: PixelFlasher_Win_2019.exe
          path: dist/PixelFlasher.exe

      # Copy the artifact to a local directory
      - name: Copy Windows Artifact locally
        if: ${{ env.ACT }} # Only run this step when not running in GitHub Actions
        run: |
          cp dist/PixelFlasher dist/PixelFlasher.exe

      # # Create a release
      # - name: Create Release
        # id: create_release
        # # uses: actions/create-release@v1
        # uses: ncipollo/release-action@v1.11.1
        # # env:
          # # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          # tag: ${{ github.ref }}
          # # release_name: Release ${{ github.ref }}
          # # name: Release ${{ github.ref }}
          # name: Release ${{ github.ref }}
          # allowUpdates: "true"
          # draft: false
          # prerelease: true

      # # Upload the Windows artifact to release
      # - name: Upload Windows Artifact to release
        # uses: shogo82148/actions-upload-release-asset@v1
        # # uses: actions/upload-release-asset@v1
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
          # upload_url: ${{ steps.create_release.outputs.upload_url }}
          # asset_path: dist/PixelFlasher.exe
          # asset_name: PixelFlasher.exe
          # asset_content_type: application/zip
          # # asset_content_type: application/octet-stream

